### ISSUE TITLE
Support for dates

### ISSUE THREAD

**Issue by stanim** [ulalka/excel-formulas-calculator#1]
How could dates be supported? Common use cases:

- if A1 and A2 store dates, A2-A1 should give the difference in days
- YEARFRAC

**Comment by ulalka** [comment]
Hi!
Give me couple of days, i will support it :)

**Comment by ulalka** [comment]
> if A1 and A2 store dates, A2-A1 should give the difference in days

Excel already stores dates as sequential serial numbers so they can be used in calculations. 
E.g. 
`A1` stores `44303`, its a 2021-04-17
`A2` stores `44304`, its a 2021-04-18

A2 - A1 = 44304 - 44303 = 1 days

**Comment by ulalka** [comment]
@stanim 
Can you tell me what other functions you need for dates except YEARFRAC?
