### ISSUE TITLE
support for ROW() function

### ISSUE THREAD

**Issue by masykur8d** [ulalka/excel-formulas-calculator#10]
I am using efc for calculating the formulas in python. It seems that efc has not supported the ROW() function as I get an error:

`efc.rpn_builder.parser.operands.FunctionNotSupported: Code 306. Function "ROW" not found among available functions. Formula: IF(INDEX(row_data!$B$1:$Z$1000,ROW(A5)-3,MATCH("LABEL",row_data!$B$1:$Z$1,0))="","",INDEX(row_data!$B$1:$Z$1000,ROW(A5)-3,MATCH("LABEL",row_data!$B$1:$Z$1,0)))`

Is it possible to add this function? Thanks

**Comment by ulalka** [comment]
Done :)
https://pypi.org/project/excel-formulas-calculator/0.2.8/

Check it, please

**Comment by masykur8d** [comment]
Awesome. Thanks
